[package]
name = "boa_ffi"
description = "A small Diplomat-based FFI crate for Boa"
publish = false
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
diplomat = "0.15.0"
diplomat-runtime = "0.15.1"

[lib]
crate-type = ["cdylib", "rlib"]

[[example]]
name = "demo"
path = "examples/demo.rs"

[lints]
workspace = true
